### ISSUE TITLE
Ouverture en Belgique

### ISSUE THREAD

**Issue by cyberlecgui** [Xav-74/verisure#2]
Bonjour,

Merci pour le plugin Verisure Jeedom, pensez-vous l'ouvrir en Belgique également ?

Bien à vous
Guillaume

**Comment by Xav-74** [comment]
Bonjour Guillaume,

Oui c'est en effet prévu. Mais comme je ne dispose pas de ce type d'alarme, il faut que je trouve quelqu'un qui me fasse confiance et me donne un accès temporaire à son installation :)
Je devrais avoir un peu de temps fin août.

Xav

**Comment by cyberlecgui** [comment]
Pas de soucis c’est un accès lecture ou écriture ?


Guillaume Lecomte

**Comment by Xav-74** [comment]
Les 2 ! Lecture pour l'analyse du matériel (affichage des modules dans le plugin) et écriture pour des tests d'activation / désactivation

**Comment by Xav-74** [comment]
Je prépare une version dev qui servira de base puis je te contacte par Skype pour des premiers tests.
J'essaie de faire ca pour la fin de semaine

**Comment by cyberlecgui** [comment]
Ok mon pseudo skype est : cyberlecgui

**Comment by Xav-74** [comment]
ça marche je t'invite dans la semaine ;)

**Comment by Xav-74** [comment]
Je n'arrive pas à te trouver dans Skype ?
Peux-tu essayer de ton côté ?
Mon pseudo : xaviercharles74

J'ai finalisé la partie interface du plugin pour le nouveau type d'alarme et j'ai avancé sur la partie connexion au cloud Verisure. J'aurais besoin de faire des tests de connexion (et uniquement connexion) ce week-end. Jouable pour toi ?

**Comment by cyberlecgui** [comment]
Bonjour,

Je t’ai envoyé une invitation.

Bien à toi
Guillaume

**Comment by Xav-74** [comment]
Hello Guillaume
Peux-tu jeter un oeil sur Skype stp ;)
Merci

**Comment by Xav-74** [comment]
Intégration de ce matériel Verisure OK avec la dernière version stable
