### ISSUE TITLE
Journal d'activité en UTC

### ISSUE THREAD

**Issue by saintfrater** [Xav-74/verisure#3]
Bonjour,

lorsque je regardes le journal d'activités, je constate que l'heure du log est en UTC et non en "local time".

je suppose que c'est le format de l'API, mais est-il possible "d'offseter" le temps?

merci

**Comment by Xav-74** [comment]
Hello,
Tu es sur quel type d'alarme ? 1 ou 2 ?
Et quel pays ?
Xav

**Comment by saintfrater** [comment]
Bonjour,Je suis sur une V2 pays belgique, par contre j'ai n'ai pas le choix du pays dans l'interface de configuration.Frater
-------- Message d'origine --------De : Xav-74 <notifications@github.com> Date : 22/12/20  14:03  (GMT+01:00) À : Xav-74/verisure <verisure@noreply.github.com> Cc : Frater <frater@nox-rhea.org>, Author <author@noreply.github.com> Objet : Re: [Xav-74/verisure] Journal d'activité en UTC (#3) 
Hello,
Tu es sur quel type d'alarme ? 1 ou 2 ?
Et quel pays ?
Xav

**Comment by Xav-74** [comment]
OK
C'est normal pour le pays, c'est automatique en v2.
Et je n'ai pas le souci en v1 :)
Il faut donc que je regarde car je récupère un json avec l'ensemble des informations fourni par Verisure. A priori en UTC donc.
Tu pourrais m'envoyer le log en mode debug correspondant à cette requête ? Car je ne dispose pas de ce matériel :)
On passe en MP pour plus de sécu ;)

**Comment by saintfrater** [comment]
J'ai envoyé le mail avec le log.

bien à toi,
Frater

**Comment by Xav-74** [comment]
Bugfix poussé sur la beta de ce matin.
Je te laisse tester et me dire si c'est ok ;)

Xav

**Comment by saintfrater** [comment]
Version du GiHub installé, et les times codes sont correctes :D

je clos le bug.

**Comment by Xav-74** [comment]
Cool ;)
Je pousserai en stable d'ici qq jours, le temps de finir encore qq modifs. Je te préviendrai.

**Comment by Xav-74** [comment]
Tu peux repasser en stable ;)
