### ISSUE TITLE
Image request support from motion detector/cam (v2) - HomeKit

### ISSUE THREAD

**Issue by spectrazureus** [Xav-74/verisure#4]
This is a feature request. The Homebridge Verisure plugin cannot request images from the motion detector with built-in camera V2 (the current devices installed by Verisure in France).
I am in touch with @ptz0n because he has developed a homebridge plugin to be used with Apple Homekit. 
I was wondering if you current code supports MFA ?
I filled out an enhancement request on https://github.com/ptz0n for https://github.com/ptz0n/homebridge-verisure, maybe you could help him/us  to add image request support to both v1 & v2 devices ?
Thanks a lot in avance. I am a big fan of your work.

**Comment by Xav-74** [comment]
Hi @spectrazureus
Thanks for your message.
Could you please give me the type of your alarm ?
this one (type 1) :
![alarm_verisure_type1](https://user-images.githubusercontent.com/56156622/144304103-10c253a6-b132-40a7-9467-0e458d845cfb.png)
or this one (type 2) :
![alarm_verisure_type2](https://user-images.githubusercontent.com/56156622/144304167-24fe17e9-0754-4885-a947-593983231242.png)

The feature "PhotoRequest" is only available in my plugin with the type 1.
This is in progress for the type 2 but I haven't this material so I need an account to access it. Not simple :)

And I confirm my code doesn't support MFA for type 2.

Xav

**Comment by spectrazureus** [comment]
Hi @Xav-74

Mine is type 1 (to be installed this month)
Does it mean tyoe1 is older than type2 or it depends on the country ?
So MFA is only required for type 2 ?
@ptz0n developed MFA support FYI
Your homebridge plug-in works out of the box or only for jeedom ?

Alexandre

**Comment by Xav-74** [comment]
Hello @spectrazureus 

Type 1 is no older ou newer than type 2, just different.
Generally, type 1 are installed in south Europe (Spain, Portugal, Italy, France...) and type 2 in notrh Europe (UK, Belgium, Sweden, Norway).
But it happens sometime that type 2 was installed in France.

Concerning MFA, I don't see this feature with type 1 at this time but maybe I'm wrong :)

Concerning my plugin, it is **only for Jeedom**. But it is configuerd to work with the Hombridge plugin **for Jeedom** !
If I understand well, it's not your case ?

Xav

**Comment by spectrazureus** [comment]
Hello
I am looking for a plug-in for homebridge to expose alarm items etc in
HomeKit
I will have type 1 soon installed but another guy ptz0n lacks image request
support in his plug-in
Maybe you could help him to add this feature ?
Except if I can you  use your plug-in for my setup ?

**Comment by Xav-74** [comment]
# #https://github.com/ptz0n/homebridge-securitas-direct/issues/10

**Comment by spectrazureus** [comment]
Hi @Xav-74/verisure ***@***.***>
My alarm is v1, and will be installed next week.
I would love to use your image request feature, but I need to use Eric's
plugin ?
I cannot use your plugin on my homebridge instance in docker to expose
Verisure v1 devices & images in Apple Homekit, correct ?
Did eric reply to you ? If not, is it complicated to add image support to
his plugin ? I have some dev skills (basic)

Best
Alex

**Comment by spectrazureus** [comment]
I have finally setup a VM (not a container because of nebz plugin not
supported on docker), installed Jeedom,installed your jeedom plugin, then
installed Nebz plugin (disabled for now).
I suspect only the arm/disarm functions of the alarm will be visible in the
Apple Home ? I am expecting the verisure technician next week, so I can
test then
Even if you can get images in Jeedom, that's not visible through Homekit ?
Maybe I need to ask Nebz ?
Pls advise thx
Alex

**Comment by Xav-74** [comment]
Hi Alex,

I confirm that the feature "photo request" is only available through my plugin in Jeedom : 
![image](https://user-images.githubusercontent.com/56156622/145357282-18d30167-1174-4ae1-b46d-0115923cbade.png)

In Apple Home, you only have arm/disarm functions and status information :  
![image](https://user-images.githubusercontent.com/56156622/145357531-474e51fd-002c-41b3-bcdc-ad5351cf36b8.png)
 
I don't know very good HomeKit but it seems that a characteristic types "photo" doesn't exist :  https://developer.apple.com/documentation/homekit/hmcharacteristic/characteristic_types
@NebzHB will be the good person for your question :)

Xav

**Comment by NebzHB** [comment]
Indeed, there is no Photo Characteristic or Service in Homekit.

@Xav-74 do you put the image in a folder or something ? if yes, @spectrazureus there is third party plugins you may want to play with : https://github.com/christian-fei/homebridge-image-to-camera (but the image need to have always the same name) or if you're comfortable with ffmpeg you may do it in homebridge-camera-ffmpeg.

**Comment by Xav-74** [comment]
The image is upload in the folder /data with the format YYMMDD_HHMMSS_smatrplugID_x.jpg
x = ID of the smartplug

**Comment by NebzHB** [comment]
That will not work then, these plugins needs the image file name to have always the same name.

**Comment by spectrazureus** [comment]
Thanks guys.
I am familiar with ffmpeg with hikvision cams I have in Spain in my 2ndary
house but here requesting, accessing still images generated by Verisure
motion sensor w/ embedded cam is a different story looks like. Looking at
some forum still image captures are supported by homekit.
:(

**Comment by spectrazureus** [comment]
Thanks @Xav-74/verisure ***@***.***>
So we don't expose, motion sensors when a movement is detected etc ?
I was dreaming of seeing (except maybe still pics) the rest of the devices
installed in my house by Verisure, smoke detector, etc.

**Comment by NebzHB** [comment]
@spectrazureus yes it's supported through the camera (when you don't open the stream, there is a snapshot of the camera displayed in the room, that plugin i mentioned could do that...) but we've discussed with @Xav-74 and it seems that verisure doesn't allow to ask for that picture too often... once every 30min max. that would not be usefull in your case...

**Comment by spectrazureus** [comment]
could be sufficient every 30min, as I have Arlo cam in the entrance.
I suppose this won't work out of the box ? need some changes in the plugin ?

**Comment by Xav-74** [comment]
@spectrazureus unfortunately, Verisure don't allow access to real time information of smartplugs (door/windows sensors, motion sensors,...). Even the alarm triggering is not detected  in my plugin (or other using these API) :(

**Comment by Xav-74** [comment]
@spectrazureus your Arlo cam is sold by Verisure too ?
I have not integrated this material in my plugin yet. 
I have some Arlo cam at home, but they are independant from Verisure !

**Comment by spectrazureus** [comment]
ptz0n created a native plugin for Verisure/homekit, he doesn't support
still images indeed, but probably the same arm/disarm basic functions
I will compare soon
In fact, I was looking for a new alarm system (remotely managed) but
that I can expose in homekit, maybe I am dreaming :)

**Comment by spectrazureus** [comment]
yes
looks like we can access those Arlo/verisure cam independently

**Comment by Xav-74** [comment]
In my view, the best experience is to use the plugin homebridge-verisure for basic functions and the native integration of arlo cams to watch videos :

![image0](https://user-images.githubusercontent.com/56156622/145377336-ae131f66-f07a-4f37-a67b-22e6ccfdc7b2.png)

**Comment by spectrazureus** [comment]
THANKS
You mean the one developed by ptz0n ?

**Comment by spectrazureus** [comment]
when I spoke to Eric, he told me this:  seems to me that you have a
Securitas Direct installation. This plugin is for Vbox installations.
Sorry for the confusion. If that's the case, please create an issue
here instead:

https://github.com/ptz0n/homebridge-securitas-direct

I am confused now which plugin shall I use ?

**Comment by spectrazureus** [comment]
hi, I am unable to use  homebridge-verisure, doesn't work.
What's your setup ?
I've tried Jeedom (on a synology VM) with your plugin + nebz plugin : added
the bridge & accessory: not ok
I've tried to use directly homebridge-verisure on my docker, seems to poll
alarm status, but nothing showing up in Homekit
Erik told me I should use homebridge-securitas-direct plugin directly:
tried also on docker homebridge: same nothing visible in Homekit
I am really lost here  ...
Could you pls help ?
Thx

**Comment by NebzHB** [comment]
I think you're misconfiguring docker, you HAVE to be in Host/macvlan mode !!!

**Comment by NebzHB** [comment]
you have to understand that homebridge (homekit in fact) works with multicast, and multicast is not routable !

**Comment by spectrazureus** [comment]
now I can see the alarm listed
don't know what happened
I can see my house/alarm with Plugin Verisure auto-configuré
I can see the arm/disarm command in homekit
but when I enabled it,  I don't receive any notifications from MyVerisure
App unlike when I use the app

**Comment by Xav-74** [comment]
You won't receive any notifications from MyVerisure app when you use my plugin or homebridge-securitas-direct plugin !
Because the unofficial API used simulate MyVerisure app ! That means Verisure think you'are using their app and so they don't send any notifications !

**Comment by spectrazureus** [comment]
thx !

What about using the plugin (the direct & vbox one) from ptz0n ? same
features ?

**Comment by Xav-74** [comment]
Same features, but only for alarm type 2 !
Not compatible with your system !

**Comment by spectrazureus** [comment]
ok so using jeedom, xav & nebz plugin was the answer :)
thanks a lot
BTW Arlo cam needs (I have a single one) a base station for homekit
support, but in jeedom, looks like a plugin can use the cam directly ?
What do you use for your arlo cams ?
thx

**Comment by Xav-74** [comment]
Correct answer :)
Concerning Arlo base station, it is mandatory for Homekit!
If you want to use your cam directly in Jeedom, you have to use the arlo plugin from  @mips2648
[Documentation](https://mips2648.github.io/jeedom-plugins-docs/arlo/en_US/)

**Comment by Xav-74** [comment]
If you agree, I close this issue.
You can re-open if necessary

**Comment by spectrazureus** [comment]
I use míps
But can exhaust batteries super Fast

**Comment by spectrazureus** [comment]
Yes pls close

**Comment by Xav-74** [comment]
I have a scenario with Jeedom which active my cams only when my alarm is on.
Batteries last at least 4 to 6 months

**Comment by spectrazureus** [comment]
I am interested, could you pls share it ?
btw- nebz homebridge plugin doesn't seem to work well with mips plugin
(works well). I cannot add/see arlo cam in homekit using mips/nebz
combination ...
Do you use such combinations?
thx a lot

**Comment by spectrazureus** [comment]
thanks. I need to buy a base station then ...
