### ISSUE TITLE
Sensor status

### ISSUE THREAD

**Issue by Arsiezis** [Xav-74/verisure#5]
Hello,
Is it possible to get status from sensor like when we press the central button on the station ? For example, to know if a windows is open.
I'm in France, so I configured the plugin with the type 1.
I've been waiting for this for a long time and it's really nice when used with Alexa. Of course only to activate the alarm :)

**Comment by Xav-74** [comment]
Hello @Arsiezis ,
Unfortunately, this feature is not available with alarms type 1 :(
The sensors communicate only with the station (local) and I have no information about sensor status on Verisure servers.
Maybe in a next release of Verisure app !
