### ISSUE TITLE
Le plugin ne communique plus

### ISSUE THREAD

**Issue by kl3sk** [Xav-74/verisure#8]
Bonjour,

J'ai l'impression que le plugin (ou en face) ne communique plus.

J'ai désinstallé/réinstallé le plugin mais rien n'y fait.

Version Jeedom: 4.315
Version du plugin: 2022-10-18 10:05:11

Je trouve pas de log associé au plugin.

**Comment by Xav-74** [comment]
Bonjour,

En effet, les API Verisure ont complètement changé. Je dois réécrire le plugin pour les prendre en compte et gérer également la double authentification. C’est en cours

Xav

**Comment by kl3sk** [comment]
Ok, super nouvelle merci.

Je pense que c'est réalisable, car sur l'application (IOs dans mon cas), il ne demande pas de 2FA.

J'attends avec impatience 😄

**Comment by enzofrnt** [comment]
Si besoin d'aide pour faire des tests n'hésitez pas.

**Comment by Xav-74** [comment]
En beta pour les alarmes type 1 ;)
Il manque juste la demande d'images qui ne devrait pas tarder.

**Comment by enzofrnt** [comment]
Ok, super. 

Comment je peux installer la version beta ?

**Comment by nleroy-adexos** [comment]
Bravo @Xav-74 . Franchement merci pour votre investissement.
Ca refonctionne pour moi avec la beta et un clic sur le bouton 2FA.

**Comment by Xav-74** [comment]
@enzofrnt : sur Jeedom, tu vas sur le menu plugins, puis market et tu recherches Verisure. Puis tu cliques sur "Installer beta". Attention, il faut avoir activer les betas dans les paramètres du market

@nleroy-adexos : merci ;)

**Comment by kl3sk** [comment]
Bonsoir @Xav-74, je viens de migrer vers la beta, tout semble fonctionner.

Je reviendrai le cas échéant.

Un grand merci à toi pour ton travail.

**Comment by Xav-74** [comment]
Nouvelle version beta avec prise en charge des demandes de photos ! Travail terminé pour le type 1 ! 
je me mets sur le type 2 en fin de semaine 😜

**Comment by Xav-74** [comment]
OK il y a du y avoir un souci avec la génération de l'idDevice (string aléatoire).
Peux tu allez dans le répertoire /plugins/verisure/data et supprimer le fichier qui doit s'appeler device_TON NUM INSTALL.json
Puis retenter une authentification ?

**Comment by nleroy-adexos** [comment]
Le JSON dans ce fichier était rempli de valeurs `null`.
Avec ton manip (suppression, authentification) c'est parfait !
```
───────── Authentification 2FA terminée avec succès ─────────
───────── Mise à jour statut OK ─────────
```
Encore un immense merci !

**Comment by kl3sk** [comment]
> OK il y a du y avoir un souci avec la génération de l'idDevice (string aléatoire). Peux tu allez dans le répertoire /plugins/verisure/data et supprimer le fichier qui doit s'appeler device_TON NUM INSTALL.json Puis retenter une authentification ?

Ca pourraits être incessant de document cette astuce 😉

**Comment by Xav-74** [comment]
Je vais même faire mieux 😜
Je vais rajouter un bouton pour suppression des cookies en cas de plantage. Ça permettra de pouvoir relancer une authentification 2FA forcée

**Comment by kl3sk** [comment]
Que demander de plus 😁

**Comment by Xav-74** [comment]
C’est en ligne ! Si tout va bien je bascule en stable vendredi 😜
